-- phpMyAdmin SQL Dump
-- version 5.1.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Creato il: Ott 13, 2022 alle 17:43
-- Versione del server: 5.7.24
-- Versione PHP: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `smartlensv1`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `detailsen5descriptors`
--

CREATE TABLE `detailsen5descriptors` (
  `id` varchar(200) NOT NULL,
  `detail-name` varchar(100) NOT NULL,
  `artwork` varchar(100) NOT NULL,
  `author` varchar(100) NOT NULL,
  `image` text NOT NULL,
  `detail-icon` text NOT NULL,
  `description` text NOT NULL,
  `audio-guide` varchar(200) DEFAULT NULL,
  `video` varchar(200) DEFAULT NULL,
  `artwork-id` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dump dei dati per la tabella `detailsen5descriptors`
--

INSERT INTO `detailsen5descriptors` (`id`, `detail-name`, `artwork`, `author`, `image`, `detail-icon`, `description`, `audio-guide`, `video`, `artwork-id`) VALUES
('./Particolari immagini\\Annunciazione (Leonardo)\\0_0.png', 'Trees', 'Annunciation', 'Leonardo da Vinci', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail0_0.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail0_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Annunciazione (Leonardo)\\original.png'),
('./Particolari immagini\\Annunciazione (Leonardo)\\0_1.png\r\n', 'Virgin Mary', 'Annunciation', 'Leonardo da Vinci', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/Vergine.jpg', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Annunciazione (Leonardo)\\original.png'),
('./Particolari immagini\\Annunciazione (Leonardo)\\1_0.png', 'Angel', 'Annunciation', 'Leonardo da Vinci', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/Angelo.jpg', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail1_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Annunciazione (Leonardo)\\original.png'),
('./Particolari immagini\\Annunciazione (Leonardo)\\Angelo.png', 'Angel', 'Annunciation\r\n', 'Leonardo da Vinci', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/Angelo.jpg', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail1_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Annunciazione (Leonardo)\\original.png'),
('./Particolari immagini\\Annunciazione (Leonardo)\\original.png', 'Full painting', 'Annunciation', 'Leonardo da Vinci', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/seed_000.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Annunciazione (Leonardo)\\original.png'),
('./Particolari immagini\\Annunciazione (Leonardo)\\Vergine.png', 'Virgin Mary', 'Annunciation', 'Leonardo da Vinci', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/Vergine.jpg', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Annunciazione%20(Leonardo)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Annunciazione (Leonardo)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\0_0.png', 'Mercury', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Mercurio.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail0_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\1_0.png', 'Three Graces', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Tre%20Grazie.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail1_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\1_1.png', 'Zephyrus, Chloris and Flora', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Primavera%20Zefiro%20e%20Clori.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail1_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\central.png', 'Venus', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Venere.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\Cupido.png', 'Cupid', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Cupido.jpg', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Icona%20cupido.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\Mercurio.png', 'Mercury', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Mercurio.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail0_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\original.png', 'Full Painting', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/seed_000.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\Tre Grazie.png', 'Three Graces', 'Spring', 'Botticelli\r\n', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Tre%20Grazie.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail1_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\Venere.png', 'Venus', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Venere.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Primavera (Botticelli)\\Zefiro Clori e Primavera.png', 'Zephyrus, Chloris and Flora\r\n', 'Spring', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/Primavera%20Zefiro%20e%20Clori.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Primavera%20(Botticelli)/detail1_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Primavera (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\0_0.png', 'Zephyrus and Chloris', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/Zefiro.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/detail0_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\0_1.png', 'One of the Graces', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/Grazie.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\central.png', 'Venus', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/Venere.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/central.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\original.png', 'Full painting', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/seed_000.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/central.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\Una delle Grazie.png', 'One of the Graces', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/Grazie.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\Venere.png', 'Venus', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/Venere.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/central.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere (Botticelli)\\Zefiro e Clori.png', 'Zephyrus and Chloris', 'Birth of Venus', 'Botticelli', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/Zefiro.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20(Botticelli)/detail0_0.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere (Botticelli)\\original.png'),
('./Particolari immagini\\Venere di Urbino (Tiziano)\\0_1.png', 'Maids', 'Venus of Urbino', 'Titian', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20di%20Urbino%20(Tiziano)/detail0_1.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20di%20Urbino%20(Tiziano)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere di Urbino (Tiziano)\\original.png'),
('./Particolari immagini\\Venere di Urbino (Tiziano)\\Domestica.png\r\n', 'Maids', 'Venus of Urbino', 'Titian', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20di%20Urbino%20(Tiziano)/detail0_1.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20di%20Urbino%20(Tiziano)/detail0_1.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, './Particolari immagini\\Venere di Urbino (Tiziano)\\original.png'),
('./Particolari immagini\\Venere di Urbino (Tiziano)\\original.png', 'Full painting', 'Venus of Urbino', 'Titian', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20di%20Urbino%20(Tiziano)/seed_000.png', 'https://raw.githubusercontent.com/EleonoraRistori/camera-app/main/Icone%20Particolari/Venere%20di%20Urbino%20(Tiziano)/Venere.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', NULL, NULL, '');

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `detailsen5descriptors`
--
ALTER TABLE `detailsen5descriptors`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
